"""empty message

Revision ID: 573a35c3c67b
Revises: 
Create Date: 2025-07-19 11:04:27.361392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573a35c3c67b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
